### ISSUE TITLE
Better code/template/less reuse of frontend components

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1237]
There's a lot of unnecessary duplication throughout the frontend, one example being the page sidebar templates, which are all pretty much identical so should share the same generic template.

### TODO
- [x] Add '.app' top-level view for main content area (so can do things like control scrolling universally by setting the height)
- [ ] File upload view (to support assets, plugins etc.)
- [ ] Toggle switch (e.g. https://proto.io/freebies/onoff/)
- [ ] Generic 'picker' view for plugins

**Comment by taylortom** [comment]
Also fits into Mike's atomic design

**Comment by taylortom** [comment]
https://proto.io/freebies/onoff/

**Comment by taylortom** [comment]
Too vague
